env:
  - CXX=g++-5
language: node_js
node_js:
  - "8"
services:
  - docker
sudo: required
before_install:
  - npm i -g node-gyp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5