version: '3'
services:
  kite-api:
    depends_on:
      - kite-mongo
      - kite-redis
    build: ./kite-api
    volumes:
       - "/var/run/docker.sock:/var/run/docker.sock"
       - "/app/kite/public-html/:/app/public/"
    networks:
        kite:
          aliases:
            - kiteapi
        kiteprivate:
  kite-nginx:
    depends_on:
      - kite-api
    build: ./kite-nginx
#    volumes:
#      - "${KITE_SSLCERT}:/etc/nginx/cert.crt"
#      - "${KITE_SSLKEY}:/etc/nginx/key.key"
    ports:
     - "443:443"
     - "80:80"
    networks:
        kite:
          aliases:
            - kitenginx
  kite-redis:
    build: ./kite-redis
    sysctls:
      net.core.somaxconn: 1024
    networks:
      kiteprivate:
        aliases:
          - kiteredis
  kite-mongo:
    environment:
      MONGO_INITDB_DATABASE: kite
    build: ./kite-mongo
    networks:
      kite-private:
        aliases:
          - kitemongo
networks:
  kite:
    driver: bridge
  kiteprivate:
    driver: bridge