version: '3'
services:
  kite-api:
    build: ./kite-api
    volumes:
       - "/var/run/docker.sock:/var/run/docker.sock"
       - "/app/kite/public-html/:/app/public/"
    networks:
        kite:
          aliases:
            - kiteapi
  kite-nginx:
    build: ./kite-nginx
    volumes:
       - "${KITE_SSLCERT}:/etc/nginx/cert.crt"
       - "${KITE_SSLKEY}:/etc/nginx/key.key"
    ports:
     - "443:443"
     - "80:80"
    networks:
        kite:
          aliases:
            - kitenginx
  kite-redis:
    build: ./kite-redis
    ports:
      - "6379:6379"
    networks:
      kite:
        aliases:
          - kiteredis
networks:
  kite:
    driver: bridge