version: '3'
services:
  kite-api:
    build: ./kite-api
    volumes:
       - "C:/public-html/:/app/public/"
    networks:
        kite:
          aliases:
            - kiteapi
  kite-nginx:
    build: ./kite-nginx
#    volumes:
#       - "${KITE_SSLCERT}:/etc/nginx/cert.crt"
#       - "${KITE_SSLKEY}:/etc/nginx/key.key"
    ports:
     - "443:443"
     - "8080:80"
    networks:
        kite:
          aliases:
            - kitenginx
  kite-redis:
    build: ./kite-redis
    sysctls:
      net.core.somaxconn: 1024
    networks:
      kite:
        aliases:
          - kiteredis
networks:
  kite:
    driver: bridge